### ISSUE TITLE
Thoughts on Material Design UX?

### ISSUE THREAD

**Issue by NiXXeD** [webchatty/webchatty#11]
Been implementing MD a ton at work using [angular material](https://material.angularjs.org/latest/#/) and it's been a really solid experience. Both from a development standpoint and for UX too.

I could pretty trivially convert the top bar into a material bar and add a collapsed sidenav for much better navigation options. The current top bar has virtually no responsiveness to it and I've been pretty annoyed with it for a long time.

Bonus points would be lots of good animation and a cleaner/newer look and feel for the site. I would keep a dark theme that would look very similar to the current, but it'd have nice drop shadows and depth on things like MD defines.

Thoughts?

**Comment by electroly** [comment]
How well will it integrate visually with Shacknews?  In particular I'm concerned about how well a sidebar would work with the Shack site in all the places where they may want to embed the chatty.

**Comment by boarder2** [comment]
I guess it could work.  Depending on how easy it is to style.  Seems like just jumping in without some pretty heavy styling would just result in "another clean themed" site.  Which I guess may not be bad.

At the very least, it'd be interesting to play around with.

**Comment by electroly** [comment]
I think plain vanilla styling may be desirable here.  Whether it's either embedded in the Shacknews website, or embedded in someone else's website, it'll always need to serve the needs of the containing site which has its own style.  If our stuff is too distinctive, it could be hard to integrate.
